server:
  port: 8001
logging:
  level:
    web: debug
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
     # defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka
#主机名称：服务名称修改（也就是将IP地址，换成可读性高的名字）
  instance:
    instance-id: payment8001 #添加此处
#访问信息有IP信息提示，（就是将鼠标指针移至payment8001，payment8002名下，会有IP地址提示）
    prefer-ip-address: true


