server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yuandeguo/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master
##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
  rabbitmq:
    host: 192.168.111.10
    port: 5672
    username: guest
    password: guest
management:
  endpoints: #暴露bus刷新配置的端点 http://localhost:3344/actuator/busrefresh
    web:
      exposure:
        include: 'bus-refresh'
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka