server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: 192.168.111.10
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit

      bindings:
        outputRabbit-out-0:
          binder: defaultRabbit
          destination: destination-test-rabbit
        inputRabbit1-in-0:
          binder: defaultRabbit
          destination: destination-test-rabbit
          group: group1
        inputRabbit2-in-0:
          binder: defaultRabbit
          destination: destination-test-rabbit
          group: group2
          content-type: application/json
      function:
        definition: inputRabbit1;inputRabbit2
      default-binder: defaultRabbit









eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8801.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
